name: CI
on:
  pull_request:
    branches:
      - master
      - next

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - uses: denoland/setup-deno@v2
        with:
          deno-version: "2.6.3"
      - name: Format
        run: make fmt-check
      - name: Lint
        run: make lint
      - name: Check
        run: make check
      - name: Test
        run: make test
